#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "find ~" | pv -qL 10 
find ~
echo -n "vulnerable:2> "
sleep 1
echo "find ~|xargs file" | pv -qL 10 
find ~|xargs file
echo -n "vulnerable:2> "
sleep 1
echo "/usr/bin/copy" | pv -qL 10 
/usr/bin/copy
echo -n "vulnerable:2> "
sleep 1
echo "/usr/bin/copy --help" | pv -qL 10 
/usr/bin/copy --help
echo -n "vulnerable:2> "
sleep 1
echo "cat /.dockerenv" | pv -qL 10 
cat /.dockerenv
echo -n "vulnerable:2> "
sleep 1
echo "file /usr/bin/copy" | pv -qL 10 
file /usr/bin/copy
echo -n "vulnerable:2> "
sleep 1
echo "cat /usr/bin/copy" | pv -qL 10 
cat /usr/bin/copy
exit
