#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "whoami" | pv -qL 10 
whoami
echo -n "vulnerable:2> "
sleep 1
echo "uname -a" | pv -qL 10 
uname -a
echo -n "vulnerable:2> "
sleep 1
echo "cat /etc/passwd" | pv -qL 10 
cat /etc/passwd
echo -n "vulnerable:2> "
sleep 1
echo "ls -la /" | pv -qL 10 
ls -la /
echo -n "vulnerable:2> "
sleep 1
echo "ls -la /root" | pv -qL 10 
ls -la /root
echo -n "vulnerable:2> "
sleep 1
echo "ls -la" | pv -qL 10 
ls -la
echo -n "vulnerable:2> "
sleep 1
echo "pwd" | pv -qL 10 
pwd
echo -n "vulnerable:2> "
sleep 1
echo "find / -perm /u=s,g=s" | pv -qL 10 
find / -perm /u=s,g=s
exit
