#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "ls -la stuff" | pv -qL 10 
ls -la stuff
echo -n "vulnerable:2> "
sleep 1
echo "/usr/bin/copy --help" | pv -qL 10 
/usr/bin/copy --help
echo -n "vulnerable:2> "
sleep 1
echo "head -n 15 /usr/bin/copy" | pv -qL 10 
head -n 15 /usr/bin/copy
exit
