#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "find / -perm /4000 2>/dev/null" | pv -qL 10 
find / -perm /4000 2>/dev/null
echo -n "vulnerable:2> "
sleep 1
echo "id" | pv -qL 10 
id
echo -n "vulnerable:2> "
sleep 1
echo "ls -la" | pv -qL 10 
ls -la
exit
