#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "file /usr/bin/copy" | pv -qL 10 
file /usr/bin/copy
echo -n "vulnerable:2> "
sleep 1
echo "ls -la stuff/*" | pv -qL 10 
ls -la stuff/*
echo -n "vulnerable:2> "
sleep 1
echo "strings /usr/bin/copy" | pv -qL 10 
strings /usr/bin/copy
exit
