#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "mkdir stuff/testing" | pv -qL 10 
mkdir stuff/testing
echo -n "vulnerable:2> "
sleep 1
echo "echo \"freddie\" >> stuff/testing/test" | pv -qL 10 
echo "freddie" >> stuff/testing/test
echo -n "vulnerable:2> "
sleep 1
echo "echo \"freddie\" >> stuff/pleasework.txt" | pv -qL 10 
echo "freddie" >> stuff/pleasework.txt
echo -n "vulnerable:2> "
sleep 1
echo "touch stuff/nice.txt" | pv -qL 10 
touch stuff/nice.txt
echo -n "vulnerable:2> "
sleep 1
echo "ln -sf /home/dev_user/stuff/nice.txt /etc/shadow" | pv -qL 10 
ln -sf /home/dev_user/stuff/nice.txt /etc/shadow
exit
