#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "ls -a /tmp /var/tmp /var/backups /var/mail/ /var/spool/mail/ /root" | pv -qL 10 
ls -a /tmp /var/tmp /var/backups /var/mail/ /var/spool/mail/ /root
echo -n "vulnerable:2> "
sleep 1
echo "find /home -user root 2>/dev/null" | pv -qL 10 
find /home -user root 2>/dev/null
echo -n "vulnerable:2> "
sleep 1
echo "for d in `find /var /etc /home /root /tmp /usr /opt /boot /sys -type d -user \$(whoami) 2>/dev/null`; do find \$d ! -user `whoami` -exec ls -l {} \\; 2>/dev/null; done" | pv -qL 10 
for d in `find /var /etc /home /root /tmp /usr /opt /boot /sys -type d -user $(whoami) 2>/dev/null`; do find $d ! -user `whoami` -exec ls -l {} \; 2>/dev/null; done
echo -n "vulnerable:2> "
sleep 1
echo "find / -type f -user root ! -perm -o=r 2>/dev/null" | pv -qL 10 
find / -type f -user root ! -perm -o=r 2>/dev/null
echo -n "vulnerable:2> "
sleep 1
echo "find / '(' -type f -or -type d ')' '(' '(' -user \$USER ')' -or '(' -perm -o=w ')' ')' ! -path \"/proc/*\" ! -path \"/sys/*\" ! -path \"\$HOME/*\" 2>/dev/null" | pv -qL 10 
find / '(' -type f -or -type d ')' '(' '(' -user $USER ')' -or '(' -perm -o=w ')' ')' ! -path "/proc/*" ! -path "/sys/*" ! -path "$HOME/*" 2>/dev/null
echo -n "vulnerable:2> "
sleep 1
echo "fils=`find / -type f \\( -name \"*_history\" -o -name \".sudo_as_admin_successful\" -o -name \".profile\" -o -name \"*bashrc\" -o -name \"httpd.conf\" -o -name \"*.plan\" -o -name \".htpasswd\" -o -name \".git-credentials\" -o -name \"*.rhosts\" -o -name \"hosts.equiv\" -o -name \"Dockerfile\" -o -name \"docker-compose.yml\" \\) 2>/dev/null`Hidden files" | pv -qL 10 
fils=`find / -type f \( -name "*_history" -o -name ".sudo_as_admin_successful" -o -name ".profile" -o -name "*bashrc" -o -name "httpd.conf" -o -name "*.plan" -o -name ".htpasswd" -o -name ".git-credentials" -o -name "*.rhosts" -o -name "hosts.equiv" -o -name "Dockerfile" -o -name "docker-compose.yml" \) 2>/dev/null`Hidden files
echo -n "vulnerable:2> "
sleep 1
echo "find / -type f -iname \".*\" -ls 2>/dev/null" | pv -qL 10 
find / -type f -iname ".*" -ls 2>/dev/null
echo -n "vulnerable:2> "
sleep 1
echo "ls -alhR /var/www/ 2>/dev/null" | pv -qL 10 
ls -alhR /var/www/ 2>/dev/null
echo -n "vulnerable:2> "
sleep 1
echo "ls -alhR /srv/www/htdocs/ 2>/dev/null" | pv -qL 10 
ls -alhR /srv/www/htdocs/ 2>/dev/null
echo -n "vulnerable:2> "
sleep 1
echo "ls -alhR /usr/local/www/apache22/data/" | pv -qL 10 
ls -alhR /usr/local/www/apache22/data/
echo -n "vulnerable:2> "
sleep 1
echo "ls -alhR /opt/lampp/htdocs/ 2>/dev/null" | pv -qL 10 
ls -alhR /opt/lampp/htdocs/ 2>/dev/null
echo -n "vulnerable:2> "
sleep 1
echo "find /var /etc /bin /sbin /home /usr/local/bin /usr/local/sbin /usr/bin /usr/games /usr/sbin /root /tmp -type f \\( -name \"*backup*\" -o -name \"*\\.bak\" -o -name \"*\\.bck\" -o -name \"*\\.bk\" \\) 2>/dev/null" | pv -qL 10 
find /var /etc /bin /sbin /home /usr/local/bin /usr/local/sbin /usr/bin /usr/games /usr/sbin /root /tmp -type f \( -name "*backup*" -o -name "*\.bak" -o -name "*\.bck" -o -name "*\.bk" \) 2>/dev/null
echo -n "vulnerable:2> "
sleep 1
echo "aureport --tty | grep -E \"su |sudo \" | sed -E \"s,su|sudo,\${C}[1;31m&\${C}[0m,g\"" | pv -qL 10 
aureport --tty | grep -E "su |sudo " | sed -E "s,su|sudo,${C}[1;31m&${C}[0m,g"
echo -n "vulnerable:2> "
sleep 1
echo "grep -RE 'comm=\"su\"|comm=\"sudo\"' /var/log* 2>/dev/null" | pv -qL 10 
grep -RE 'comm="su"|comm="sudo"' /var/log* 2>/dev/null
echo -n "vulnerable:2> "
sleep 1
echo "ls -al /etc/cron* /etc/at*" | pv -qL 10 
ls -al /etc/cron* /etc/at*
echo -n "vulnerable:2> "
sleep 1
echo "cd /home" | pv -qL 10 
cd /home
echo -n "vulnerable:2> "
sleep 1
echo "ls -la" | pv -qL 10 
ls -la
exit
