#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "/usr/bin/copy /root/html/ ./" | pv -qL 10 
/usr/bin/copy /root/html/ ./
echo -n "vulnerable:2> "
sleep 1
echo "ls -la ./stuff/" | pv -qL 10 
ls -la ./stuff/
echo -n "vulnerable:2> "
sleep 1
echo "ls -la" | pv -qL 10 
ls -la
exit
