#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "find / -perm /6000 2>/dev/null" | pv -qL 10 
find / -perm /6000 2>/dev/null
echo -n "vulnerable:2> "
sleep 1
echo "cat /etc/group" | pv -qL 10 
cat /etc/group
echo -n "vulnerable:2> "
sleep 1
echo "id" | pv -qL 10 
id
echo -n "vulnerable:2> "
sleep 1
echo "ps aux | grep root" | pv -qL 10 
ps aux | grep root
echo -n "vulnerable:2> "
sleep 1
echo "\$ ps -elf | grep root" | pv -qL 10 
$ ps -elf | grep root
echo -n "vulnerable:2> "
sleep 1
echo "cat /etc/cron*" | pv -qL 10 
cat /etc/cron*
echo -n "vulnerable:2> "
sleep 1
echo "cat /etc/cron.d/*" | pv -qL 10 
cat /etc/cron.d/*
echo -n "vulnerable:2> "
sleep 1
echo "cat /etc/cron.daily/*" | pv -qL 10 
cat /etc/cron.daily/*
echo -n "vulnerable:2> "
sleep 1
echo "cat /etc/cron.hourly/*" | pv -qL 10 
cat /etc/cron.hourly/*
echo -n "vulnerable:2> "
sleep 1
echo "cat /etc/cron.monthly/*" | pv -qL 10 
cat /etc/cron.monthly/*
echo -n "vulnerable:2> "
sleep 1
echo "cat /etc/crontab" | pv -qL 10 
cat /etc/crontab
echo -n "vulnerable:2> "
sleep 1
echo "cat /etc/at.allow" | pv -qL 10 
cat /etc/at.allow
echo -n "vulnerable:2> "
sleep 1
echo "cat /etc/at.deny" | pv -qL 10 
cat /etc/at.deny
echo -n "vulnerable:2> "
sleep 1
echo "cat /etc/anacrontab" | pv -qL 10 
cat /etc/anacrontab
echo -n "vulnerable:2> "
sleep 1
echo "ls -ahlR /home/" | pv -qL 10 
ls -ahlR /home/
echo -n "vulnerable:2> "
sleep 1
echo "\$ ls -ahlR /root/" | pv -qL 10 
$ ls -ahlR /root/
echo -n "vulnerable:2> "
sleep 1
echo "find / -xdev -type d -perm -0002 -ls 2> /dev/null" | pv -qL 10 
find / -xdev -type d -perm -0002 -ls 2> /dev/null
echo -n "vulnerable:2> "
sleep 1
echo "find / -xdev -type f -perm -0002 -ls 2> /dev/null" | pv -qL 10 
find / -xdev -type f -perm -0002 -ls 2> /dev/null
echo -n "vulnerable:2> "
sleep 1
echo "sudo -l" | pv -qL 10 
sudo -l
echo -n "vulnerable:2> "
sleep 1
echo "id" | pv -qL 10 
id
exit
