#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "find / -user dev_user 2>/dev/null" | pv -qL 10 
find / -user dev_user 2>/dev/null
echo -n "vulnerable:2> "
sleep 1
echo "ls -la /etc/skel" | pv -qL 10 
ls -la /etc/skel
echo -n "vulnerable:2> "
sleep 1
echo "cd /etc/skel" | pv -qL 10 
cd /etc/skel
echo -n "vulnerable:2> "
sleep 1
echo "cat *" | pv -qL 10 
cat *
echo -n "vulnerable:2> "
sleep 1
echo "ls -la" | pv -qL 10 
ls -la
echo -n "vulnerable:2> "
sleep 1
echo "cat .pwd.lock" | pv -qL 10 
cat .pwd.lock
exit
