#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "ls -la ./stuff/" | pv -qL 10 
ls -la ./stuff/
echo -n "vulnerable:2> "
sleep 1
echo "ls -la /usr/bin/copy" | pv -qL 10 
ls -la /usr/bin/copy
echo -n "vulnerable:2> "
sleep 1
echo "file /usr/bin/copy" | pv -qL 10 
file /usr/bin/copy
echo -n "vulnerable:2> "
sleep 1
echo "cat /usr/bin/copy" | pv -qL 10 
cat /usr/bin/copy
exit
