#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "id" | pv -qL 10 
id
echo -n "vulnerable:2> "
sleep 1
echo "whoami" | pv -qL 10 
whoami
echo -n "vulnerable:2> "
sleep 1
echo "pwd" | pv -qL 10 
pwd
echo -n "vulnerable:2> "
sleep 1
echo "ls -la" | pv -qL 10 
ls -la
echo -n "vulnerable:2> "
sleep 1
echo "cat /etc/passwd" | pv -qL 10 
cat /etc/passwd
echo -n "vulnerable:2> "
sleep 1
echo "find / -perm /4000 2>/dev/null" | pv -qL 10 
find / -perm /4000 2>/dev/null
echo -n "vulnerable:2> "
sleep 1
echo "cat /etc/crontab" | pv -qL 10 
cat /etc/crontab
echo -n "vulnerable:2> "
sleep 1
echo "ls -la /opt" | pv -qL 10 
ls -la /opt
echo -n "vulnerable:2> "
sleep 1
echo "sudo -l" | pv -qL 10 
sudo -l
exit
