#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "base64 /usr/bin/copy" | pv -qL 10 
base64 /usr/bin/copy
echo -n "vulnerable:2> "
sleep 1
echo "/usr/bin/copy --help" | pv -qL 10 
/usr/bin/copy --help
exit
