#!/bin/bash

echo -n "vulnerable:1> "
sleep 1
echo "which nc" | pv -qL 10 
which nc
echo -n "vulnerable:1> "
sleep 1
echo "ifconfig" | pv -qL 10 
ifconfig
echo -n "vulnerable:1> "
sleep 1
echo "(cat /proc/version || uname -a ) 2>/dev/null" | pv -qL 10 
(cat /proc/version || uname -a ) 2>/dev/null
echo -n "vulnerable:1> "
sleep 1
echo "echo \$PATH" | pv -qL 10 
echo $PATH
echo -n "vulnerable:1> "
sleep 1
echo "(env || set) 2>/dev/null" | pv -qL 10 
(env || set) 2>/dev/null
echo -n "vulnerable:1> "
sleep 1
echo "cat /proc/version" | pv -qL 10 
cat /proc/version
echo -n "vulnerable:1> "
sleep 1
echo "sudo -V | grep \"Sudo ver\" | grep \"1\\.[01234567]\\.[0-9]\\+\\|1\\.8\\.1[0-9]\\*\\|1\\.8\\.2[01234567]\"" | pv -qL 10 
sudo -V | grep "Sudo ver" | grep "1\.[01234567]\.[0-9]\+\|1\.8\.1[0-9]\*\|1\.8\.2[01234567]"
echo -n "vulnerable:1> "
sleep 1
echo "grep -E \"(user|username|login|pass|password|pw|credentials)[=:]\" /etc/fstab /etc/mtab 2>/dev/null" | pv -qL 10 
grep -E "(user|username|login|pass|password|pw|credentials)[=:]" /etc/fstab /etc/mtab 2>/dev/null
echo -n "vulnerable:1> "
sleep 1
echo "which nmap aws nc ncat netcat nc.traditional wget curl ping gcc g++ make gdb base64 socat python python2 python3 python2.7 python2.6 python3.6 python3.7 perl php ruby xterm doas sudo fetch docker lxc ctr runc rkt kubectl 2>/dev/null" | pv -qL 10 
which nmap aws nc ncat netcat nc.traditional wget curl ping gcc g++ make gdb base64 socat python python2 python3 python2.7 python2.6 python3.6 python3.7 perl php ruby xterm doas sudo fetch docker lxc ctr runc rkt kubectl 2>/dev/null
echo -n "vulnerable:1> "
sleep 1
echo "ps aux" | pv -qL 10 
ps aux
echo -n "vulnerable:1> "
sleep 1
echo "crontab -l" | pv -qL 10 
crontab -l
echo -n "vulnerable:1> "
sleep 1
echo "ls -al /etc/cron* /etc/at*" | pv -qL 10 
ls -al /etc/cron* /etc/at*
echo -n "vulnerable:1> "
sleep 1
echo "cat /etc/cron* /etc/at* /etc/anacrontab /var/spool/cron/crontabs/root 2>/dev/null | grep -v \"^#\"" | pv -qL 10 
cat /etc/cron* /etc/at* /etc/anacrontab /var/spool/cron/crontabs/root 2>/dev/null | grep -v "^#"
echo -n "vulnerable:1> "
sleep 1
echo "cat /etc/passwd | cut -d: -f1" | pv -qL 10 
cat /etc/passwd | cut -d: -f1
echo -n "vulnerable:1> "
sleep 1
echo "awk -F: '(\$3 == \"0\") {print}' /etc/passwd" | pv -qL 10 
awk -F: '($3 == "0") {print}' /etc/passwd
echo -n "vulnerable:1> "
sleep 1
echo "w" | pv -qL 10 
w
echo -n "vulnerable:1> "
sleep 1
echo "lastlog" | pv -qL 10 
lastlog
echo -n "vulnerable:1> "
sleep 1
echo "for i in \$(cut -d\":\" -f1 /etc/passwd 2>/dev/null);do id \$i;done 2>/dev/null | sort" | pv -qL 10 
for i in $(cut -d":" -f1 /etc/passwd 2>/dev/null);do id $i;done 2>/dev/null | sort
echo -n "vulnerable:1> "
sleep 1
echo "systemd-run -t /bin/bash" | pv -qL 10 
systemd-run -t /bin/bash
echo -n "vulnerable:1> "
sleep 1
echo "find / -perm -4000 2>/dev/null" | pv -qL 10 
find / -perm -4000 2>/dev/null
exit
