#!/bin/bash

echo -n "vulnerable:1> "
sleep 1
echo "id" | pv -qL 10 
id
echo -n "vulnerable:1> "
sleep 1
echo "whoami" | pv -qL 10 
whoami
echo -n "vulnerable:1> "
sleep 1
echo "echo \"123\"" | pv -qL 10 
echo "123"
echo -n "vulnerable:1> "
sleep 1
echo "find . -type f -name *.txt" | pv -qL 10 
find . -type f -name *.txt
exit
