#!/bin/bash

echo -n "vulnerable:1> "
sleep 1
echo "ls -la /var/www/*" | pv -qL 10 
ls -la /var/www/*
echo -n "vulnerable:1> "
sleep 1
echo "netstat -tulpn" | pv -qL 10 
netstat -tulpn
echo -n "vulnerable:1> "
sleep 1
echo "ss -alnp" | pv -qL 10 
ss -alnp
exit
