#!/bin/bash

echo -n "vulnerable:1> "
sleep 1
echo "find /" | pv -qL 10 
find /
echo -n "vulnerable:1> "
sleep 1
echo "ls -la ~" | pv -qL 10 
ls -la ~
echo -n "vulnerable:1> "
sleep 1
echo "ls -la /root" | pv -qL 10 
ls -la /root
echo -n "vulnerable:1> "
sleep 1
echo "ls -la /" | pv -qL 10 
ls -la /
exit
