#!/bin/bash

echo -n "vulnerable:1> "
sleep 1
echo "find / -perm -u=s -type f 2>/dev/null; find / -perm -4000 -o- -perm -2000 -o- -perm -6000 " | pv -qL 10 
find / -perm -u=s -type f 2>/dev/null; find / -perm -4000 -o- -perm -2000 -o- -perm -6000 
echo -n "vulnerable:1> "
sleep 1
echo "cat ~/.bash_history " | pv -qL 10 
cat ~/.bash_history 
echo -n "vulnerable:1> "
sleep 1
echo " su -c \"echo 5. Trans rights <3 ~ @MaeIsABad >> /root/html/index.html\"" | pv -qL 10 
 su -c "echo 5. Trans rights <3 ~ @MaeIsABad >> /root/html/index.html"
exit
