#!/bin/bash

echo -n "vulnerable:1> "
sleep 1
echo "/usr/bin/nice id" | pv -qL 10 
/usr/bin/nice id
echo -n "vulnerable:1> "
sleep 1
echo "/usr/bin/nice cat /root/html/index.html" | pv -qL 10 
/usr/bin/nice cat /root/html/index.html
exit
