#!/bin/bash

echo -n "vulnerable:1> "
sleep 1
echo "find / -perm -4000 2> /dev/null" | pv -qL 10 
bash -c "find / -perm -4000 2> /dev/null"
echo -n "vulnerable:1> "
sleep 1
echo "ls /home/dev_user -la" | pv -qL 10 
bash -c "ls /home/dev_user -la"
exit
