#!/bin/bash

echo -n "vulnerable:1> "
sleep 1
echo "id" | pv -qL 10 
bash -c "id"
echo -n "vulnerable:1> "
sleep 1
echo "whoami" | pv -qL 10 
bash -c "whoami"
echo -n "vulnerable:1> "
sleep 1
echo "find / -type f -perm -04000 -ls 2> /dev/null" | pv -qL 10 
bash -c "find / -type f -perm -04000 -ls 2> /dev/null"
exit
