#!/bin/bash

echo -n "vulnerable:1> "
sleep 1
echo "id" | pv -qL 10 
bash -c "id"
echo -n "vulnerable:1> "
sleep 1
echo "ls" | pv -qL 10 
bash -c "ls"
echo -n "vulnerable:1> "
sleep 1
echo "find /" | pv -qL 10 
bash -c "find /"
exit
