#!/bin/bash

echo -n "vulnerable:1> "
sleep 1
echo "id" | pv -qL 10 
bash -c "id"
echo -n "vulnerable:1> "
sleep 1
echo "whoami" | pv -qL 10 
bash -c "whoami"
echo -n "vulnerable:1> "
sleep 1
echo "ls -lthr /root/html/" | pv -qL 10 
bash -c "ls -lthr /root/html/"
echo -n "vulnerable:1> "
sleep 1
echo "ps aux" | pv -qL 10 
bash -c "ps aux"
echo -n "vulnerable:1> "
sleep 1
echo "ps -efax" | pv -qL 10 
bash -c "ps -efax"
exit
