#!/bin/bash

echo -n "vulnerable:1> "
sleep 1
echo "id" | pv -qL 10 
id
echo -n "vulnerable:1> "
sleep 1
echo "find / -perm -4000 2>/dev/null" | pv -qL 10 
find / -perm -4000 2>/dev/null
echo -n "vulnerable:1> "
sleep 1
echo "mount -v" | pv -qL 10 
mount -v
echo -n "vulnerable:1> "
sleep 1
echo "sudo -l -l" | pv -qL 10 
sudo -l -l
exit
